defaults:
  - _self_
  - model: mlp
  - pde: dw_forward
  - optimizer: default
  - trainer: default
  - plot: plotly

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb:
  project: "tDWfPINN"
  entity: null
  mode: "disabled" # Default to disabled for dev, user can enable
  group: null

seed: 42
work_dir: ${hydra:runtime.cwd}
debug: false
