defaults:
  - _self_
  - model: mlp
  - pde: dw_forward
  - optimizer: default
  - trainer: default
  - plot: plotly

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${wandb.project}-${wandb.name}/${now:%Y-%m-%d_%H-%M-%S}

wandb:
  project: "tDWfPINN"
  entity: null
  mode: "disabled" # Default to disabled for dev, user can enable
  name: ${pde.method}
  group: null

seed: 42
work_dir: ${hydra:runtime.cwd}
debug: false
